import { c as create_ssr_component, v as validate_component } from "../../chunks/ssr.js";
const Contact_svelte_svelte_type_style_lang = "";
const css$1 = {
  code: "section.svelte-16giuc5.svelte-16giuc5{background-color:var(--black-blue);color:var(--white)}form.svelte-16giuc5.svelte-16giuc5{display:flex;flex-direction:column;gap:1rem;margin-top:3rem}form.svelte-16giuc5 label.svelte-16giuc5{margin-bottom:0.5rem}form.svelte-16giuc5 input.svelte-16giuc5,textarea.svelte-16giuc5.svelte-16giuc5{background-color:var(--black-blue);color:var(--black-blue);border:1px var(--light-grey) solid;border-radius:5px;padding:1rem 2rem 1rem 0.5rem;font-size:1rem;color:var(--white)}form.svelte-16giuc5 input.svelte-16giuc5::placeholder,textarea.svelte-16giuc5.svelte-16giuc5::placeholder{color:var(--light-grey)}.contact-grid.svelte-16giuc5.svelte-16giuc5{align-content:start}.contact-grid-item.svelte-16giuc5.svelte-16giuc5{margin-bottom:3rem}.contact-icon.svelte-16giuc5.svelte-16giuc5{width:32px;height:32px}.contact-sub-text.svelte-16giuc5.svelte-16giuc5{font-size:1.125rem;font-weight:700;margin:1rem 0}.link.svelte-16giuc5.svelte-16giuc5{color:var(--white)}",
  map: null
};
const Contact = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css$1);
  return `<section class="svelte-16giuc5"><div class="container"><div class="section-kicker" data-svelte-h="svelte-86jhnw">Contact Us</div> <h2 data-svelte-h="svelte-1374y9q">How can we help?</h2> <p data-svelte-h="svelte-4bhcsa">We&#39;re here to answer any questions you may have. Contact us today!</p> <div class="grid-col-2"> <form name="contact" method="POST" data-netlify="true" class="svelte-16giuc5"><p data-svelte-h="svelte-1w6dzt6"><label class="svelte-16giuc5">Your Name: <input type="text" name="name" class="svelte-16giuc5"></label></p> <p data-svelte-h="svelte-5e6ngx"><label class="svelte-16giuc5">Your Email: <input type="email" name="email" class="svelte-16giuc5"></label></p> <p><label class="svelte-16giuc5">Your Role: <select name="role[]" multiple><option value="leader" data-svelte-h="svelte-26mlre">Leader</option><option value="follower" data-svelte-h="svelte-1ty4gbi">Follower</option></select></label></p> <p data-svelte-h="svelte-1pqesy9"><label class="svelte-16giuc5">Message: <textarea name="message" class="svelte-16giuc5"></textarea></label></p> <p data-svelte-h="svelte-fric0v"><button type="submit">Send</button></p></form> <div class="grid-col-2 contact-grid svelte-16giuc5" data-svelte-h="svelte-3paslq"><div class="contact-grid-item svelte-16giuc5"><img class="contact-icon svelte-16giuc5" src="/images/email.svg" alt="envelope"> <div class="contact-sub-text svelte-16giuc5">Email</div> <a href="mailto:info@dovedesign.io" class="link svelte-16giuc5">info@dovedesign.io</a></div> <div class="contact-grid-item svelte-16giuc5"><img class="contact-icon svelte-16giuc5" src="/images/phone.svg" alt="phone"> <div class="contact-sub-text svelte-16giuc5">Phone</div> <a href="tel:07540599633" class="link svelte-16giuc5">07540599633</a></div> <div class="contact-grid-item svelte-16giuc5"><img class="contact-icon svelte-16giuc5" src="/images/linkedin.svg" alt="LinkedIn"> <div class="contact-sub-text svelte-16giuc5">LinkedIn</div> <a href="https://www.linkedin.com/company/dovedesignweb/" target="_blank" class="link svelte-16giuc5">@dovedesignweb</a></div></div></div></div> </section>`;
});
const _page_svelte_svelte_type_style_lang = "";
const css = {
  code: "header.svelte-ezaod.svelte-ezaod.svelte-ezaod{position:relative;padding:4rem 0;height:100vh;overflow:hidden}.home-hero.svelte-ezaod.svelte-ezaod.svelte-ezaod{display:grid;grid-template-columns:1fr 1fr}.home-hero-text.svelte-ezaod.svelte-ezaod.svelte-ezaod{max-width:600px}.home-hero-text.svelte-ezaod p.svelte-ezaod.svelte-ezaod{margin-bottom:1rem}header.svelte-ezaod img.svelte-ezaod.svelte-ezaod{position:absolute;left:550px;top:50px;height:100%;width:100%}.button-wrap.svelte-ezaod.svelte-ezaod.svelte-ezaod{display:flex;gap:1rem}.grid-image.svelte-ezaod.svelte-ezaod.svelte-ezaod{width:100%;max-width:635px}.home-hero-icon-grid.svelte-ezaod.svelte-ezaod.svelte-ezaod{display:grid;grid-template-columns:1fr 1fr;grid-gap:1rem;margin:3rem 0}.icon-item-wrapper.svelte-ezaod img.svelte-ezaod.svelte-ezaod{height:50px;width:50px;margin-bottom:1rem}.grid-col-3.svelte-ezaod div.svelte-ezaod img.svelte-ezaod{margin-bottom:1rem}.grid-col-3.svelte-ezaod div.svelte-ezaod h3.svelte-ezaod{font-size:2rem}.cta-full-width.svelte-ezaod.svelte-ezaod.svelte-ezaod{background-image:url(/images/cta-banner.webp);background-position:center;background-size:cover;background-repeat:no-repeat;width:100%;height:420px;text-align:center;color:var(--white);position:relative;display:flex;align-items:center;justify-content:center}.banner-overlay.svelte-ezaod.svelte-ezaod.svelte-ezaod{background-color:rgba(47, 101, 229, 0.9);width:100%;height:100%;position:absolute;top:0}.z-index.svelte-ezaod.svelte-ezaod.svelte-ezaod{z-index:10}.testimonials.svelte-ezaod.svelte-ezaod.svelte-ezaod{margin:2rem 0 0 0}.testimonial-item.svelte-ezaod.svelte-ezaod.svelte-ezaod{display:flex;gap:1rem;margin:2rem 0}.testimonial-item.svelte-ezaod .bold.svelte-ezaod.svelte-ezaod{font-weight:700}.testimonial-item.svelte-ezaod img.svelte-ezaod.svelte-ezaod{width:56px;height:56px}.star-wrap.svelte-ezaod.svelte-ezaod.svelte-ezaod{margin:2rem 0}.star-wrap.svelte-ezaod img.svelte-ezaod.svelte-ezaod{width:24px}",
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<header class="svelte-ezaod" data-svelte-h="svelte-1rgba0a"><div class="container svelte-ezaod"><div class="home-hero svelte-ezaod"><div class="home-hero-text svelte-ezaod"><h1>Transforming businesses with <span>stunning websites</span></h1> <p class="svelte-ezaod">At Dove Design, we specialise in creating visually appealing and highly functional Webflow
					websites that help businesses succeed online. Our team of experts combines design and
					technology to deliver exceptional user experiences.</p> <div class="button-wrap svelte-ezaod"><a class="button" href="/">Schedule a Call</a> <a class="is-secondary" href="/work">Our Work</a></div></div> <img src="/images/flowga-portfolio.png" alt="Flowga studios screenshots" class="svelte-ezaod"></div></div></header> <section data-svelte-h="svelte-lf2iyi"><div class="container svelte-ezaod"><div class="grid-col-2 svelte-ezaod"><div class="home-hero-text svelte-ezaod"><p class="section-kicker svelte-ezaod">How can we help</p> <h2>Experts in Web <span>Design</span> &amp; Web <span>Development</span></h2> <p class="svelte-ezaod">At Dove Design, we offer a range of services to help businesses succeed online. Our team
					of experts specialises in Webflow design, development, and maintenance, ensuring that your
					website is visually stunning, user-friendly, and always up to date.</p> <p class="svelte-ezaod">Whether you need a brand new website or want to enhance your existing one, we have the
					skills and expertise to deliver exceptional results.</p> <div class="home-hero-icon-grid svelte-ezaod"><div class="icon-item-wrapper svelte-ezaod"><img src="/images/design.svg" alt="paint pallette" class="svelte-ezaod"> <h3 class="svelte-ezaod">Web Design</h3> <p class="svelte-ezaod">Our team of skilled designers transforms your ideas into visually stunning,
							user-friendly websites that not only meet but exceed your expectations.</p></div> <div class="icon-item-wrapper svelte-ezaod"><img src="/images/responsive.svg" alt="responsive web design" class="svelte-ezaod"> <h3 class="svelte-ezaod">Web Development</h3> <p class="svelte-ezaod">We harness the power of Webflow&#39;s no-code platform to build websites that are not only
							visually appealing but also incredibly responsive and easy to manage.</p></div> <div class="icon-item-wrapper svelte-ezaod"><img src="/images/hosting.svg" alt="hosting websites" class="svelte-ezaod"> <h3 class="svelte-ezaod">Website Hosting</h3> <p class="svelte-ezaod">Enjoy the fastest, most scalable hosting technology for your business powered by
							Amazon Web Services.</p></div> <div class="icon-item-wrapper svelte-ezaod"><img src="/images/medal.svg" alt="blue medal" class="svelte-ezaod"> <h3 class="svelte-ezaod">Training</h3> <p class="svelte-ezaod">We offer virtual training sessions to your staff on how to update the website with
							video tutorials.</p></div></div> <a class="button" href="/contact">Contact us</a></div> <img class="grid-image svelte-ezaod" src="/images/section-image.webp" alt="Flowga studios screenshots"></div></div></section> <section data-svelte-h="svelte-1mpdu2w"><div class="container"><div class="grid-col-2"><div><p class="section-kicker">Why Dove Design</p> <h2>Unlock the potential of the web for your <span>business</span></h2></div> <p>Webflow is a powerful tool that empowers businesses to create stunning and functional
				websites without the need for coding. With its intuitive interface and robust features,
				Webflow streamlines the web design process and allows businesses to focus on what they do
				best.</p></div> <div class="grid-col-3 svelte-ezaod"><div><img src="/images/tick.svg" alt="tick" class="svelte-ezaod"> <h3 class="svelte-ezaod">Empowered control</h3> <p>With Webflow, clients can make updates and edits to their websites without relying on
					developers. This hands-on approach saves time and money, putting you in charge of your
					digital presence.</p></div> <div><img src="/images/tick.svg" alt="tick" class="svelte-ezaod"> <h3 class="svelte-ezaod">Responsive websites</h3> <p>Webflow ensures your website looks stunning and functions seamlessly on all devices.
					Mobile users will have a smooth and engaging experience.</p></div> <div><img src="/images/tick.svg" alt="tick" class="svelte-ezaod"> <h3 class="svelte-ezaod">Lightning-fast hosting</h3> <p>Powered by Amazon Web Services with 100+ server sites globally, content is delivered in
					milliseconds.</p></div> <div><img src="/images/tick.svg" alt="tick" class="svelte-ezaod"> <h3 class="svelte-ezaod">Search engine visibility</h3> <p>Webflow incorporates SEO best practices, ensuring your website ranks well on search
					engines. This translates to increased organic traffic and potential customers.</p></div> <div><img src="/images/tick.svg" alt="tick" class="svelte-ezaod"> <h3 class="svelte-ezaod">Top grade security</h3> <p>Comes with SSL and two-factor authentication out of the box. You can also password protect
					individual pages.</p></div> <div><img src="/images/tick.svg" alt="tick" class="svelte-ezaod"> <h3 class="svelte-ezaod">First class support</h3> <p>Webflow&#39;s responsive support team is ready to assist with any questions or issues. You&#39;ll
					have peace of mind knowing there&#39;s a dedicated team to help you achieve your website
					goals.</p></div></div> <a class="button" href="/contact">Contact us</a></div></section> <section class="cta-full-width svelte-ezaod" data-svelte-h="svelte-xiw4j9"><div class="banner-overlay svelte-ezaod"></div> <div class="container z-index svelte-ezaod"><h2>Web Design Experts</h2> <p>Empower Your Online Identity with Tailored Design Magic</p> <button class="is-secondary">View Our Work</button></div></section> <section data-svelte-h="svelte-1bxazxf"><div class="container svelte-ezaod"><h2>Happy Clients</h2> <p>Hear what our clients have to say about our Webflow services</p> <div class="grid-col-2 testimonials svelte-ezaod"><div class="svelte-ezaod"><div class="star-wrap svelte-ezaod"><img src="/images/star.svg" alt="blue star" class="svelte-ezaod"> <img src="/images/star.svg" alt="blue star" class="svelte-ezaod"> <img src="/images/star.svg" alt="blue star" class="svelte-ezaod"> <img src="/images/star.svg" alt="blue star" class="svelte-ezaod"> <img src="/images/star.svg" alt="blue star" class="svelte-ezaod"></div> <p>&quot;I cannot praise Dove Design enough. From the very start of this project they were very
					professional, providing great support, advice and guidance at all times. The process was
					quick and completed before the deadline and the final product was brilliant. Thank you so
					much for everything.&quot;</p> <div class="testimonial-item svelte-ezaod"><img src="/images/cpm-logo.png" alt="Community Peer Mentors Logo" class="svelte-ezaod"> <div class="testimonial-text"><p class="bold svelte-ezaod">Jim Cunningham</p> <p>Community Peer Mentors</p></div></div></div> <div class="svelte-ezaod"><div class="star-wrap svelte-ezaod"><img src="/images/star.svg" alt="blue star" class="svelte-ezaod"> <img src="/images/star.svg" alt="blue star" class="svelte-ezaod"> <img src="/images/star.svg" alt="blue star" class="svelte-ezaod"> <img src="/images/star.svg" alt="blue star" class="svelte-ezaod"> <img src="/images/star.svg" alt="blue star" class="svelte-ezaod"></div> <p>&quot;We commissioned our new website with Dove Design and they have been fantastic to work
					with on this major project. They were brilliant to work with during development of the
					project, were quick to respond to any queries we had and were always available to contact.
					We would recommend to anyone.&quot;</p> <div class="testimonial-item svelte-ezaod"><img src="/images/pcc-logo.png" alt="Community Peer Mentors Logo" class="svelte-ezaod"> <div class="testimonial-text"><p class="bold svelte-ezaod">Steve White</p> <p>Durham Police &amp; Crime Commissioner</p></div></div></div></div></div></section> ${validate_component(Contact, "Contact").$$render($$result, {}, {}, {})}`;
});
export {
  Page as default
};
