import { c as create_ssr_component } from "../../chunks/ssr.js";
const _page_svelte_svelte_type_style_lang = "";
const css = {
  code: "header.svelte-11whlg1.svelte-11whlg1.svelte-11whlg1{position:relative;padding:4rem 0;height:100vh;overflow:hidden}.home-hero.svelte-11whlg1.svelte-11whlg1.svelte-11whlg1{display:grid;grid-template-columns:1fr 1fr}.home-hero-text.svelte-11whlg1.svelte-11whlg1.svelte-11whlg1{max-width:500px}.home-hero-text.svelte-11whlg1 p.svelte-11whlg1.svelte-11whlg1{margin-bottom:1rem}header.svelte-11whlg1 img.svelte-11whlg1.svelte-11whlg1{position:absolute;left:550px;top:50px;height:100%;width:100%}.button-wrap.svelte-11whlg1.svelte-11whlg1.svelte-11whlg1{display:flex;gap:1rem}.home-section.svelte-11whlg1.svelte-11whlg1.svelte-11whlg1{display:grid;grid-template-columns:1fr 1fr}.home-section.svelte-11whlg1 img.svelte-11whlg1.svelte-11whlg1{width:100%;max-width:635px}.home-hero-icon-grid.svelte-11whlg1.svelte-11whlg1.svelte-11whlg1{display:grid;grid-template-columns:1fr 1fr;grid-gap:1rem}.icon-item-wrapper.svelte-11whlg1 img.svelte-11whlg1.svelte-11whlg1{height:50px;width:50px;margin-bottom:1rem}.grid-col-3.svelte-11whlg1 div.svelte-11whlg1 img.svelte-11whlg1{margin-bottom:1rem}.grid-col-3.svelte-11whlg1 div.svelte-11whlg1 h3.svelte-11whlg1{font-size:2rem}",
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<header class="svelte-11whlg1" data-svelte-h="svelte-1sedcsa"><div class="container svelte-11whlg1"><div class="home-hero svelte-11whlg1"><div class="home-hero-text svelte-11whlg1"><h1>Transforming businesses with <span>stunning websites</span></h1> <p class="svelte-11whlg1">At Dove Design, we specialise in creating visually appealing and highly functional Webflow
					websites that help businesses succeed online. Our team of experts combines design and
					technology to deliver exceptional user experiences.</p> <div class="button-wrap svelte-11whlg1"><button>Schedule a call</button> <button class="is-secondary">Our Work</button></div></div> <img src="/images/flowga-portfolio.png" alt="Flowga studios screenshots" class="svelte-11whlg1"></div></div></header> <section data-svelte-h="svelte-k4m14"><div class="container svelte-11whlg1"><div class="home-section svelte-11whlg1"><div class="home-hero-text svelte-11whlg1"><p class="section-kicker svelte-11whlg1">How can we help</p> <h2>Experts in Web <span>Design</span> &amp; Web <span>Development</span></h2> <p class="svelte-11whlg1">At Dove Design, we offer a range of services to help businesses succeed online. Our team
					of experts specialises in Webflow design, development, and maintenance, ensuring that your
					website is visually stunning, user-friendly, and always up to date.</p> <p class="svelte-11whlg1">Whether you need a brand new website or want to enhance your existing one, we have the
					skills and expertise to deliver exceptional results.</p> <div class="home-hero-icon-grid svelte-11whlg1"><div class="icon-item-wrapper svelte-11whlg1"><img src="/images/design.svg" alt="paint pallette" class="svelte-11whlg1"> <h3 class="svelte-11whlg1">Web Design</h3> <p class="svelte-11whlg1">Our team of skilled designers transforms your ideas into visually stunning,
							user-friendly websites that not only meet but exceed your expectations.</p></div> <div class="icon-item-wrapper svelte-11whlg1"><img src="/images/responsive.svg" alt="responsive web design" class="svelte-11whlg1"> <h3 class="svelte-11whlg1">Web Development</h3> <p class="svelte-11whlg1">We harness the power of Webflow&#39;s no-code platform to build websites that are not only
							visually appealing but also incredibly responsive and easy to manage.</p></div> <div class="icon-item-wrapper svelte-11whlg1"><img src="/images/hosting.svg" alt="hosting websites" class="svelte-11whlg1"> <h3 class="svelte-11whlg1">Website Hosting</h3> <p class="svelte-11whlg1">Enjoy the fastest, most scalable hosting technology for your business powered by
							Amazon Web Services.</p></div> <div class="icon-item-wrapper svelte-11whlg1"><img src="/images/medal.svg" alt="blue medal" class="svelte-11whlg1"> <h3 class="svelte-11whlg1">Training</h3> <p class="svelte-11whlg1">We offer virtual training sessions to your staff on how to update the website with
							video tutorials.</p></div></div> <a class="button" href="/contact">Contact us</a></div> <img src="/images/section-image.webp" alt="Flowga studios screenshots" class="svelte-11whlg1"></div></div></section> <section data-svelte-h="svelte-w7rnoc"><div class="container"><div class="grid-col-2"><div><p class="section-kicker">Why Dove Design</p> <h2>Unlock the potential of the web for your <span>business</span></h2></div> <p>Webflow is a powerful tool that empowers businesses to create stunning and functional
				websites without the need for coding. With its intuitive interface and robust features,
				Webflow streamlines the web design process and allows businesses to focus on what they do
				best.</p></div> <div class="grid-col-3 svelte-11whlg1"><div><img src="/images/tick.svg" alt="" class="svelte-11whlg1"> <h3 class="svelte-11whlg1">Empowered control</h3> <p>With Webflow, clients can make updates and edits to their websites without relying on
					developers. This hands-on approach saves time and money, putting you in charge of your
					digital presence.</p></div> <div><img src="/images/tick.svg" alt="" class="svelte-11whlg1"> <h3 class="svelte-11whlg1">Responsive websites</h3> <p>Webflow ensures your website looks stunning and functions seamlessly on all devices.
					Mobile users will have a smooth and engaging experience.</p></div> <div><img src="/images/tick.svg" alt="" class="svelte-11whlg1"> <h3 class="svelte-11whlg1">Lightning-fast hosting</h3> <p>Powered by Amazon Web Services with 100+ server sites globally, content is delivered in
					milliseconds.</p></div> <div><img src="/images/tick.svg" alt="" class="svelte-11whlg1"> <h3 class="svelte-11whlg1">Search engine visibility</h3> <p>Webflow incorporates SEO best practices, ensuring your website ranks well on search
					engines. This translates to increased organic traffic and potential customers.</p></div> <div><img src="/images/tick.svg" alt="" class="svelte-11whlg1"> <h3 class="svelte-11whlg1">Top grade security</h3> <p>Comes with SSL and two-factor authentication out of the box. You can also password protect
					individual pages.</p></div> <div><img src="/images/tick.svg" alt="" class="svelte-11whlg1"> <h3 class="svelte-11whlg1">First class support</h3> <p>Webflow&#39;s responsive support team is ready to assist with any questions or issues. You&#39;ll
					have peace of mind knowing there&#39;s a dedicated team to help you achieve your website
					goals.</p></div></div> <a class="button" href="/contact">Contact us</a></div> </section>`;
});
export {
  Page as default
};
