import { c as create_ssr_component, e as escape, b as add_attribute, v as validate_component } from "../../chunks/ssr.js";
import { T as Testimonials } from "../../chunks/Testimonials.js";
const Contact_svelte_svelte_type_style_lang = "";
const css$1 = {
  code: "section.svelte-bbxuzf.svelte-bbxuzf{background-color:var(--black-blue);color:var(--white)}form.svelte-bbxuzf.svelte-bbxuzf{display:flex;flex-direction:column;gap:1rem;margin-top:3rem}form.svelte-bbxuzf div.svelte-bbxuzf{display:flex;flex-direction:column}form.svelte-bbxuzf label.svelte-bbxuzf{margin-bottom:0.5rem}form.svelte-bbxuzf input.svelte-bbxuzf,textarea.svelte-bbxuzf.svelte-bbxuzf{background-color:var(--black-blue);color:var(--black-blue);border:1px var(--light-grey) solid;border-radius:5px;padding:1rem 2rem 1rem 0.5rem;font-size:1rem;color:var(--white)}form.svelte-bbxuzf input.svelte-bbxuzf::placeholder,textarea.svelte-bbxuzf.svelte-bbxuzf::placeholder{color:var(--light-grey)}form.svelte-bbxuzf button.svelte-bbxuzf{font-size:1rem;font-weight:800}.contact-grid.svelte-bbxuzf.svelte-bbxuzf{align-content:start}.contact-grid-item.svelte-bbxuzf.svelte-bbxuzf{margin-bottom:3rem}.contact-icon.svelte-bbxuzf.svelte-bbxuzf{width:32px;height:32px}.contact-sub-text.svelte-bbxuzf.svelte-bbxuzf{font-size:1.125rem;font-weight:700;margin:1rem 0}.link.svelte-bbxuzf.svelte-bbxuzf{color:var(--white)}",
  map: null
};
const Contact = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css$1);
  return `${$$result.head += `<!-- HEAD_svelte-frahok_START -->${$$result.title = `<title>Dove Design Ltd | Contact Us</title>`, ""}<meta name="description" content="We're here to answer any questions you may have. Contact us today!"><!-- HEAD_svelte-frahok_END -->`, ""} <section class="svelte-bbxuzf" data-svelte-h="svelte-rf88r5"><div class="container"><div class="section-kicker">Contact Us</div> <h2>How can we help?</h2> <p>We&#39;re here to answer any questions you may have. Contact us today!</p> <div class="grid-col-2"><form name="contact" method="POST" data-netlify-recaptcha="true" data-netlify="true" class="svelte-bbxuzf"><div class="svelte-bbxuzf"><label for="text" class="svelte-bbxuzf">Name</label> <input id="text" type="text" name="name" placeholder="Name" required class="svelte-bbxuzf"></div> <div class="svelte-bbxuzf"><label for="email" class="svelte-bbxuzf">Email</label>  <input id="email" type="email" name="email" placeholder="Email" required class="svelte-bbxuzf"></div> <div class="svelte-bbxuzf"><label for="phone" class="svelte-bbxuzf">Phone</label> <input id="phone" type="Phone" name="phone" placeholder="Phone" class="svelte-bbxuzf"></div> <div class="svelte-bbxuzf"><label for="textarea" class="svelte-bbxuzf">Message</label> <textarea id="textarea" type="textarea" name="message" placeholder="Message" required class="svelte-bbxuzf"></textarea></div> <div data-netlify-recaptcha="true" class="svelte-bbxuzf"></div> <button type="submit" class="svelte-bbxuzf">Submit Form</button></form> <div class="grid-col-2 contact-grid svelte-bbxuzf"><div class="contact-grid-item svelte-bbxuzf"><img class="contact-icon svelte-bbxuzf" src="/images/email.svg" alt="envelope"> <div class="contact-sub-text svelte-bbxuzf">Email</div> <a href="mailto:info@dovedesign.io" class="link svelte-bbxuzf">info@dovedesign.io</a></div> <div class="contact-grid-item svelte-bbxuzf"><img class="contact-icon svelte-bbxuzf" src="/images/phone.svg" alt="phone"> <div class="contact-sub-text svelte-bbxuzf">Phone</div> <a href="tel:07540599633" class="link svelte-bbxuzf">07540599633</a></div> <div class="contact-grid-item svelte-bbxuzf"><img class="contact-icon svelte-bbxuzf" src="/images/linkedin.svg" alt="LinkedIn"> <div class="contact-sub-text svelte-bbxuzf">LinkedIn</div> <a href="https://www.linkedin.com/company/dovedesignweb/" target="_blank" class="link svelte-bbxuzf">@dovedesignweb</a></div></div></div></div> </section>`;
});
const _page_svelte_svelte_type_style_lang = "";
const css = {
  code: "header.svelte-wlaw74.svelte-wlaw74.svelte-wlaw74{overflow:hidden;height:100vh;max-height:800px}.home-hero.svelte-wlaw74.svelte-wlaw74.svelte-wlaw74{display:grid;grid-template-columns:1fr 1fr;align-items:center}.home-hero-text.svelte-wlaw74.svelte-wlaw74.svelte-wlaw74{max-width:600px}.home-hero-text.svelte-wlaw74 p.svelte-wlaw74.svelte-wlaw74{margin-bottom:1rem}header.svelte-wlaw74 img.svelte-wlaw74.svelte-wlaw74{height:100%;width:100%;overflow:hidden}.button-wrap.svelte-wlaw74.svelte-wlaw74.svelte-wlaw74{display:flex;align-items:center;gap:1rem;margin-top:3rem}.button-wrap.svelte-wlaw74 a.svelte-wlaw74.svelte-wlaw74{margin-top:0}.grid-image.svelte-wlaw74.svelte-wlaw74.svelte-wlaw74{width:100%;max-width:635px}.home-hero-icon-grid.svelte-wlaw74.svelte-wlaw74.svelte-wlaw74{display:grid;grid-template-columns:1fr 1fr;grid-gap:1rem;margin:3rem 0}.icon-item-wrapper.svelte-wlaw74 img.svelte-wlaw74.svelte-wlaw74{height:50px;width:50px;margin-bottom:1rem}.grid-col-3.svelte-wlaw74 div.svelte-wlaw74 img.svelte-wlaw74{margin-bottom:1rem}.grid-col-3.svelte-wlaw74 div.svelte-wlaw74 h3.svelte-wlaw74{font-size:2rem}.cta-full-width.svelte-wlaw74.svelte-wlaw74.svelte-wlaw74{background-image:url(/images/cta-banner.jpg);background-position:center;background-size:cover;background-repeat:no-repeat;width:100%;height:420px;text-align:center;color:var(--white);position:relative;display:flex;align-items:center;justify-content:center}.banner-overlay.svelte-wlaw74.svelte-wlaw74.svelte-wlaw74{background-color:rgba(47, 101, 229, 0.9);width:100%;height:100%;position:absolute;top:0}.z-index.svelte-wlaw74.svelte-wlaw74.svelte-wlaw74{z-index:10}.is-secondary.svelte-wlaw74.svelte-wlaw74.svelte-wlaw74{margin-top:2rem}@media screen and (max-width: 961px){.home-hero.svelte-wlaw74.svelte-wlaw74.svelte-wlaw74{display:flex;flex-direction:column;gap:3rem}header.svelte-wlaw74 img.svelte-wlaw74.svelte-wlaw74{position:static;left:550px;top:50px;height:100%;width:100%}.home-hero-icon-grid.svelte-wlaw74.svelte-wlaw74.svelte-wlaw74{display:flex;flex-direction:column}}",
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let { title = "Dove Design Ltd | Home" } = $$props;
  let { description = "Test At Dove Design, we specialise in creating visually appealing and highly functional websites that help businesses succeed online." } = $$props;
  if ($$props.title === void 0 && $$bindings.title && title !== void 0)
    $$bindings.title(title);
  if ($$props.description === void 0 && $$bindings.description && description !== void 0)
    $$bindings.description(description);
  $$result.css.add(css);
  return `${$$result.head += `<!-- HEAD_svelte-1lvwc9d_START -->${$$result.title = `<title>${escape(title)}</title>`, ""}<meta name="description"${add_attribute("content", description, 0)}><!-- HEAD_svelte-1lvwc9d_END -->`, ""} <header class="svelte-wlaw74" data-svelte-h="svelte-1gqzgfk"><div class="container svelte-wlaw74"><div class="home-hero svelte-wlaw74"><div class="home-hero-text svelte-wlaw74"><h1>Transforming businesses with <span>stunning websites</span></h1> <p class="svelte-wlaw74">At Dove Design, we specialise in creating visually appealing and highly functional
					websites that help businesses succeed online. Our team of experts combines design and
					technology to deliver exceptional user experiences.</p> <div class="button-wrap svelte-wlaw74"><a class="button svelte-wlaw74" href="/contact">Contact Us</a> <a class="is-secondary svelte-wlaw74" href="/work">Our Work</a></div></div> <img src="/images/home-hero.png" alt="Dove Design Portfolio screenshots" class="svelte-wlaw74"></div></div></header> <section data-svelte-h="svelte-1qkau2c"><div class="container svelte-wlaw74"><div class="grid-col-2 svelte-wlaw74"><div class="home-hero-text svelte-wlaw74"><p class="section-kicker svelte-wlaw74">How can we help</p> <h2>Experts in Web <span>Design</span> &amp; Web <span>Development</span></h2> <p class="svelte-wlaw74">At Dove Design, we offer a range of services to help businesses succeed online. Our team
					of experts specialises in design, development, and maintenance, ensuring that your website
					is visually stunning, user-friendly, and always up to date.</p> <p class="svelte-wlaw74">Whether you need a brand new website or want to enhance your existing one, we have the
					skills and expertise to deliver exceptional results.</p> <div class="home-hero-icon-grid svelte-wlaw74"><div class="icon-item-wrapper svelte-wlaw74"><img src="/images/design.svg" alt="paint pallette" class="svelte-wlaw74"> <h3 class="svelte-wlaw74">Web Design</h3> <p class="svelte-wlaw74">Our team of skilled designers transforms your ideas into visually stunning,
							user-friendly websites that not only meet but exceed your expectations.</p></div> <div class="icon-item-wrapper svelte-wlaw74"><img src="/images/responsive.svg" alt="responsive web design" class="svelte-wlaw74"> <h3 class="svelte-wlaw74">Web Development</h3> <p class="svelte-wlaw74">We bring your website to life with custom development solutions that are tailored to
							your business needs and objectives.</p></div> <div class="icon-item-wrapper svelte-wlaw74"><img src="/images/hosting.svg" alt="hosting websites" class="svelte-wlaw74"> <h3 class="svelte-wlaw74">Website Hosting</h3> <p class="svelte-wlaw74">Enjoy the fastest, most scalable hosting technology for your business powered by super
							fast web services.</p></div> <div class="icon-item-wrapper svelte-wlaw74"><img src="/images/medal.svg" alt="blue medal" class="svelte-wlaw74"> <h3 class="svelte-wlaw74">Training</h3> <p class="svelte-wlaw74">We offer virtual training sessions to your staff on how to update the website with
							video tutorials.</p></div></div> <a class="button" href="/contact">Contact us</a></div>  <img class="grid-image svelte-wlaw74" src="/images/section-image.webp" alt="Flowga studios screenshots"></div></div></section> <section data-svelte-h="svelte-1mpdu2w"><div class="container"><div class="grid-col-2"><div><p class="section-kicker">Why Dove Design</p> <h2>Unlock the potential of the web for your <span>business</span></h2></div> <p>Webflow is a powerful tool that empowers businesses to create stunning and functional
				websites without the need for coding. With its intuitive interface and robust features,
				Webflow streamlines the web design process and allows businesses to focus on what they do
				best.</p></div> <div class="grid-col-3 svelte-wlaw74"><div><img src="/images/tick.svg" alt="tick" class="svelte-wlaw74"> <h3 class="svelte-wlaw74">Empowered control</h3> <p>With Webflow, clients can make updates and edits to their websites without relying on
					developers. This hands-on approach saves time and money, putting you in charge of your
					digital presence.</p></div> <div><img src="/images/tick.svg" alt="tick" class="svelte-wlaw74"> <h3 class="svelte-wlaw74">Responsive websites</h3> <p>Webflow ensures your website looks stunning and functions seamlessly on all devices.
					Mobile users will have a smooth and engaging experience.</p></div> <div><img src="/images/tick.svg" alt="tick" class="svelte-wlaw74"> <h3 class="svelte-wlaw74">Lightning-fast hosting</h3> <p>Powered by Amazon Web Services with 100+ server sites globally, content is delivered in
					milliseconds.</p></div> <div><img src="/images/tick.svg" alt="tick" class="svelte-wlaw74"> <h3 class="svelte-wlaw74">Search engine visibility</h3> <p>Webflow incorporates SEO best practices, ensuring your website ranks well on search
					engines. This translates to increased organic traffic and potential customers.</p></div> <div><img src="/images/tick.svg" alt="tick" class="svelte-wlaw74"> <h3 class="svelte-wlaw74">Top grade security</h3> <p>Comes with SSL and two-factor authentication out of the box. You can also password protect
					individual pages.</p></div> <div><img src="/images/tick.svg" alt="tick" class="svelte-wlaw74"> <h3 class="svelte-wlaw74">First class support</h3> <p>Webflow&#39;s responsive support team is ready to assist with any questions or issues. You&#39;ll
					have peace of mind knowing there&#39;s a dedicated team to help you achieve your website
					goals.</p></div></div> <a class="button" href="/contact">Contact us</a></div></section> <section class="cta-full-width svelte-wlaw74" data-svelte-h="svelte-1cb7zhl"><div class="banner-overlay svelte-wlaw74"></div> <div class="container z-index svelte-wlaw74"><h2>Web Design Experts</h2> <p>Empower Your Online Identity with Tailored Design Magic</p> <a href="/work"><button class="is-secondary svelte-wlaw74">View Our Work</button></a></div></section> ${validate_component(Testimonials, "Testimonials").$$render($$result, {}, {}, {})} ${validate_component(Contact, "Contact").$$render($$result, {}, {}, {})}`;
});
export {
  Page as default
};
