import { c as create_ssr_component, v as validate_component } from "../../../chunks/ssr.js";
import { T as Testimonials } from "../../../chunks/Testimonials.js";
const _page_svelte_svelte_type_style_lang = "";
const css = {
  code: "section.svelte-bbxuzf.svelte-bbxuzf{background-color:var(--black-blue);color:var(--white)}form.svelte-bbxuzf.svelte-bbxuzf{display:flex;flex-direction:column;gap:1rem;margin-top:3rem}form.svelte-bbxuzf label.svelte-bbxuzf{margin-bottom:0.5rem}form.svelte-bbxuzf input.svelte-bbxuzf,textarea.svelte-bbxuzf.svelte-bbxuzf{background-color:var(--black-blue);color:var(--black-blue);border:1px var(--light-grey) solid;border-radius:5px;padding:1rem 2rem 1rem 0.5rem;font-size:1rem;color:var(--white)}form.svelte-bbxuzf input.svelte-bbxuzf::placeholder,textarea.svelte-bbxuzf.svelte-bbxuzf::placeholder{color:var(--light-grey)}form.svelte-bbxuzf button.svelte-bbxuzf{font-size:1rem;font-weight:800}.contact-grid.svelte-bbxuzf.svelte-bbxuzf{align-content:start}.contact-grid-item.svelte-bbxuzf.svelte-bbxuzf{margin-bottom:3rem}.contact-icon.svelte-bbxuzf.svelte-bbxuzf{width:32px;height:32px}.contact-sub-text.svelte-bbxuzf.svelte-bbxuzf{font-size:1.125rem;font-weight:700;margin:1rem 0}.link.svelte-bbxuzf.svelte-bbxuzf{color:var(--white)}",
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<section class="svelte-bbxuzf"><div class="container"><div class="section-kicker" data-svelte-h="svelte-86jhnw">Contact Us</div> <h2 data-svelte-h="svelte-1374y9q">How can we help?</h2> <p data-svelte-h="svelte-4bhcsa">We&#39;re here to answer any questions you may have. Contact us today!</p> <div class="grid-col-2"><form name="contact" method="POST" data-netlify="true" class="svelte-bbxuzf"><input type="hidden" name="form-name" value="contact" class="svelte-bbxuzf"> <p data-svelte-h="svelte-1w6dzt6"><label class="svelte-bbxuzf">Your Name: <input type="text" name="name" class="svelte-bbxuzf"></label></p> <p data-svelte-h="svelte-5e6ngx"><label class="svelte-bbxuzf">Your Email: <input type="email" name="email" class="svelte-bbxuzf"></label></p> <p><label class="svelte-bbxuzf">Your Role: <select name="role[]" multiple><option value="leader" data-svelte-h="svelte-26mlre">Leader</option><option value="follower" data-svelte-h="svelte-1ty4gbi">Follower</option></select></label></p> <p data-svelte-h="svelte-1pqesy9"><label class="svelte-bbxuzf">Message: <textarea name="message" class="svelte-bbxuzf"></textarea></label></p> <p data-svelte-h="svelte-fric0v"><button type="submit" class="svelte-bbxuzf">Send</button></p></form> <div class="grid-col-2 contact-grid svelte-bbxuzf" data-svelte-h="svelte-3paslq"><div class="contact-grid-item svelte-bbxuzf"><img class="contact-icon svelte-bbxuzf" src="/images/email.svg" alt="envelope"> <div class="contact-sub-text svelte-bbxuzf">Email</div> <a href="mailto:info@dovedesign.io" class="link svelte-bbxuzf">info@dovedesign.io</a></div> <div class="contact-grid-item svelte-bbxuzf"><img class="contact-icon svelte-bbxuzf" src="/images/phone.svg" alt="phone"> <div class="contact-sub-text svelte-bbxuzf">Phone</div> <a href="tel:07540599633" class="link svelte-bbxuzf">07540599633</a></div> <div class="contact-grid-item svelte-bbxuzf"><img class="contact-icon svelte-bbxuzf" src="/images/linkedin.svg" alt="LinkedIn"> <div class="contact-sub-text svelte-bbxuzf">LinkedIn</div> <a href="https://www.linkedin.com/company/dovedesignweb/" target="_blank" class="link svelte-bbxuzf">@dovedesignweb</a></div></div></div></div></section> ${validate_component(Testimonials, "Testimonials").$$render($$result, {}, {}, {})}`;
});
export {
  Page as default
};
