import { c as create_ssr_component } from "./ssr.js";
const Contact_svelte_svelte_type_style_lang = "";
const css = {
  code: "section.svelte-bbxuzf.svelte-bbxuzf{background-color:var(--black-blue);color:var(--white)}form.svelte-bbxuzf.svelte-bbxuzf{display:flex;flex-direction:column;gap:1rem;margin-top:3rem}form.svelte-bbxuzf label.svelte-bbxuzf{margin-bottom:0.5rem}form.svelte-bbxuzf input.svelte-bbxuzf{background-color:var(--black-blue);color:var(--black-blue);border:1px var(--light-grey) solid;border-radius:5px;padding:1rem 2rem 1rem 0.5rem;font-size:1rem;color:var(--white)}form.svelte-bbxuzf input.svelte-bbxuzf::placeholder{color:var(--light-grey)}form.svelte-bbxuzf button.svelte-bbxuzf{font-size:1rem;font-weight:800}.contact-grid.svelte-bbxuzf.svelte-bbxuzf{align-content:start}.contact-grid-item.svelte-bbxuzf.svelte-bbxuzf{margin-bottom:3rem}.contact-icon.svelte-bbxuzf.svelte-bbxuzf{width:32px;height:32px}.contact-sub-text.svelte-bbxuzf.svelte-bbxuzf{font-size:1.125rem;font-weight:700;margin:1rem 0}.link.svelte-bbxuzf.svelte-bbxuzf{color:var(--white)}",
  map: null
};
const Contact = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<section class="svelte-bbxuzf" data-svelte-h="svelte-1xs0f01"><div class="container"><div class="section-kicker">Contact Us</div> <h2>How can we help?</h2> <p>We&#39;re here to answer any questions you may have. Contact us today!</p> <div class="grid-col-2"><form name="contact" netlify class="svelte-bbxuzf"><p><label class="svelte-bbxuzf">Name <input type="text" name="name" class="svelte-bbxuzf"></label></p> <p><label class="svelte-bbxuzf">Email <input type="email" name="email" class="svelte-bbxuzf"></label></p> <p><button type="submit" class="svelte-bbxuzf">Send</button></p></form> <div class="grid-col-2 contact-grid svelte-bbxuzf"><div class="contact-grid-item svelte-bbxuzf"><img class="contact-icon svelte-bbxuzf" src="/images/email.svg" alt="envelope"> <div class="contact-sub-text svelte-bbxuzf">Email</div> <a href="mailto:info@dovedesign.io" class="link svelte-bbxuzf">info@dovedesign.io</a></div> <div class="contact-grid-item svelte-bbxuzf"><img class="contact-icon svelte-bbxuzf" src="/images/phone.svg" alt="phone"> <div class="contact-sub-text svelte-bbxuzf">Phone</div> <a href="tel:07540599633" class="link svelte-bbxuzf">07540599633</a></div> <div class="contact-grid-item svelte-bbxuzf"><img class="contact-icon svelte-bbxuzf" src="/images/linkedin.svg" alt="LinkedIn"> <div class="contact-sub-text svelte-bbxuzf">LinkedIn</div> <a href="https://www.linkedin.com/company/dovedesignweb/" target="_blank" class="link svelte-bbxuzf">@dovedesignweb</a></div></div></div></div> </section>`;
});
export {
  Contact as C
};
