import { c as create_ssr_component } from "./ssr.js";
const Contact_svelte_svelte_type_style_lang = "";
const css = {
  code: "section.svelte-16giuc5.svelte-16giuc5{background-color:var(--black-blue);color:var(--white)}form.svelte-16giuc5.svelte-16giuc5{display:flex;flex-direction:column;gap:1rem;margin-top:3rem}form.svelte-16giuc5 div.svelte-16giuc5{display:flex;flex-direction:column}form.svelte-16giuc5 label.svelte-16giuc5{margin-bottom:0.5rem}form.svelte-16giuc5 input.svelte-16giuc5,textarea.svelte-16giuc5.svelte-16giuc5{background-color:var(--black-blue);color:var(--black-blue);border:1px var(--light-grey) solid;border-radius:5px;padding:1rem 2rem 1rem 0.5rem;font-size:1rem;color:var(--white)}form.svelte-16giuc5 input.svelte-16giuc5::placeholder,textarea.svelte-16giuc5.svelte-16giuc5::placeholder{color:var(--light-grey)}.contact-grid.svelte-16giuc5.svelte-16giuc5{align-content:start}.contact-grid-item.svelte-16giuc5.svelte-16giuc5{margin-bottom:3rem}.contact-icon.svelte-16giuc5.svelte-16giuc5{width:32px;height:32px}.contact-sub-text.svelte-16giuc5.svelte-16giuc5{font-size:1.125rem;font-weight:700;margin:1rem 0}.link.svelte-16giuc5.svelte-16giuc5{color:var(--white)}",
  map: null
};
const Contact = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<section class="svelte-16giuc5" data-svelte-h="svelte-1qrd1b2"><div class="container"><div class="section-kicker">Contact Us</div> <h2>How can we help?</h2> <p>We&#39;re here to answer any questions you may have. Contact us today!</p> <div class="grid-col-2"> <form name="contact" method="POST" data-netlify-recaptcha="true" data-netlify="true" class="svelte-16giuc5"><div class="svelte-16giuc5"><label for="text" class="svelte-16giuc5">Name</label> <input id="text" type="text" name="name" placeholder="Name" required class="svelte-16giuc5"></div> <div class="svelte-16giuc5"><label for="email" class="svelte-16giuc5">Email</label> <input id="email" type="email" name="email" placeholder="Email" required class="svelte-16giuc5"></div> <div class="svelte-16giuc5"><label for="phone" class="svelte-16giuc5">Phone</label> <input id="phone" type="Phone" name="phone" placeholder="Phone" class="svelte-16giuc5"></div> <div class="svelte-16giuc5"><label for="textarea" class="svelte-16giuc5">Message</label> <textarea id="textarea" type="textarea" name="message" placeholder="Message" required class="svelte-16giuc5"></textarea></div> <div data-netlify-recaptcha="true" class="svelte-16giuc5"></div> <button type="submit">Send</button></form> <div class="grid-col-2 contact-grid svelte-16giuc5"><div class="contact-grid-item svelte-16giuc5"><img class="contact-icon svelte-16giuc5" src="/images/email.svg" alt="envelope"> <div class="contact-sub-text svelte-16giuc5">Email</div> <a href="mailto:info@dovedesign.io" class="link svelte-16giuc5">info@dovedesign.io</a></div> <div class="contact-grid-item svelte-16giuc5"><img class="contact-icon svelte-16giuc5" src="/images/phone.svg" alt="phone"> <div class="contact-sub-text svelte-16giuc5">Phone</div> <a href="tel:07540599633" class="link svelte-16giuc5">07540599633</a></div> <div class="contact-grid-item svelte-16giuc5"><img class="contact-icon svelte-16giuc5" src="/images/linkedin.svg" alt="LinkedIn"> <div class="contact-sub-text svelte-16giuc5">LinkedIn</div> <a href="https://www.linkedin.com/company/dovedesignweb/" target="_blank" class="link svelte-16giuc5">@dovedesignweb</a></div></div></div></div> </section>`;
});
export {
  Contact as C
};
